{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Array.from.call(constructorSetsIndex0ConfigurableFalse, items) throws a TypeError exception Expected a TypeError but got a ReferenceError\" }\n    at ../../test262/harness/assert.js:95\n    at ../../test262/test/built-ins/Array/from/iter-set-elem-prop-err.js:48\n\n","path":"../../test262/test/built-ins/Array/from/iter-set-elem-prop-err.js","memory_kb":0,"duration":78967113}