{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a Test262Error but got a TypeError\", name: \"Test262Error\" }\n    at ../../test262/harness/assert.js:95\n    at ../../test262/test/built-ins/String/prototype/trimEnd/this-value-object-valueof-call-err.js:50\n\n","path":"../../test262/test/built-ins/String/prototype/trimEnd/this-value-object-valueof-call-err.js","memory_kb":0,"duration":262180053}