{"status":"FAIL","msg":"FAIL:\n Uncaught: { \"name\": \"Test262Error\", \"message\": \"Expected a TypeError to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/built-ins/Object/defineProperty/15.2.3.6-4-435.js:27\n\n","path":"../../test262/test/built-ins/Object/defineProperty/15.2.3.6-4-435.js","memory_kb":4512,"duration":96868854}