{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"after loop body evaluation Expected SameValue(«\"exception\"», «\"propertyName\"») to be true\" }\n    at ../../test262/harness/assert.js:49\n    at anonymous (../../test262/test/annexB/language/statements/try/catch-redeclared-for-in-var.js:27)\n\n","path":"../../test262/test/annexB/language/statements/try/catch-redeclared-for-in-var.js"}