{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"reject minus zero as extended year Expected a RangeError but got a ReferenceError\" }\n    at ../../test262/harness/assert.js:95\n    at anonymous (../../test262/test/built-ins/Temporal/Instant/from/year-zero.js:17)\n    at Object (../../test262/test/built-ins/Temporal/Instant/from/year-zero.js:16)\n\n","path":"../../test262/test/built-ins/Temporal/Instant/from/year-zero.js"}