{"status":"FAIL","msg":"FAIL:\n Uncaught: { \"name\": \"Test262Error\", \"message\": \"Expected a TypeError to be thrown but no exception was thrown at all (Testing with BigInt64Array.)\" }\n    at testWithBigIntTypedArrayConstructors (../../test262/harness/testBigIntTypedArray.js:37)\n    at ../../test262/test/built-ins/TypedArrayConstructors/internals/Delete/BigInt/key-is-out-of-bounds-strict.js:27\n\n","path":"../../test262/test/built-ins/TypedArrayConstructors/internals/Delete/BigInt/key-is-out-of-bounds-strict.js","memory_kb":0,"duration":11166190}