{"status":"FAIL","msg":"FAIL:\n Uncaught: { name: \"Test262Error\", message: \"Got `resolve` only once for each iterated value Expected SameValue(«0», «1») to be true\" }\n    at ../../test262/harness/assert.js:49\n    at ../../test262/test/built-ins/Promise/all/invoke-resolve-get-once-multiple-calls.js:40\n\n","path":"../../test262/test/built-ins/Promise/all/invoke-resolve-get-once-multiple-calls.js","memory_kb":0,"duration":206183656}