{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"onDispose is not callable Expected a TypeError but got a ReferenceError\" }\n    at ../../test262/harness/assert.js:95\n    at anonymous (../../test262/test/staging/explicit-resource-management/disposable-stack-adopt-and-defer.js:26)\n\n","path":"../../test262/test/staging/explicit-resource-management/disposable-stack-adopt-and-defer.js"}