{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a Function to be thrown but no exception was thrown at all (Testing with Function.)\" }\n    at ../../test262/harness/testBigIntTypedArray.js:37\n    at testWithBigIntTypedArrayConstructors (../../test262/test/built-ins/TypedArrayConstructors/ctors-bigint/object-arg/throws-setting-property.js:34)\n\n","path":"../../test262/test/built-ins/TypedArrayConstructors/ctors-bigint/object-arg/throws-setting-property.js"}