{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a Test262Error to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T4.js:74\n\n","path":"../../test262/test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T4.js","memory_kb":8460,"duration":51178694}